ci: sync and pass builder data to downstream tests (paused)
Signed-off-by: Pierre Fenoll <pierrefenoll@gmail.com>

diff --git a/.github/workflows/self.yml b/.github/workflows/self.yml
--- a/.github/workflows/self.yml
+++ b/.github/workflows/self.yml
@@ -9,18 +9,17 @@ jobs:
       run:
         shell: bash -euo pipefail {0}
     steps:
+    - uses: actions/checkout@v6
+
     - uses: actions-rust-lang/setup-rust-toolchain@v1
       with:
-        toolchain: stable
+        toolchain: 1.91.1
         cache-on-failure: true
     - run: docker info
     - run: docker buildx version
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
-
-    - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
       uses: actions/cache@v4
@@ -48,7 +47,27 @@ jobs:
       with:
         name: cargo-green
         path: /home/runner/.cargo/bin/cargo-green
+        if-no-files-found: error
 
+# $(login_to_readonly_hub)
+#     - run: cargo green supergreen sync
+#     - uses: actions-rust-lang/setup-rust-toolchain@v1
+#       with:
+#         toolchain: 1.90.0
+#         cache-on-failure: true
+#     - run: cargo green supergreen sync
+# $(rundeps_versions)
+#     - run: cargo green supergreen builder rm || true
+#     - run: sudo du -sh $(cargo green supergreen sync data 2>/dev/null) || true
+#     - run: sudo cp -r $(cargo green supergreen sync data 2>/dev/null) /home/runner/builder-cache || true
+#     - run: sudo chown -R $(id -u):$(id -g) /home/runner/builder-cache
+#     - run: du -sh /home/runner/builder-cache || true
+#     - run: ls -lha /home/runner/builder-cache/ || true
+#     - uses: actions/upload-artifact@v5
+#       with:
+#         name: builder-data
+#         path: /home/runner/builder-cache
+#         if-no-files-found: error
 
   installs:
     runs-on: ubuntu-latest
@@ -76,7 +95,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
 
     - name: Retrieve saved bin
       uses: actions/download-artifact@v6
@@ -89,7 +107,18 @@ jobs:
         chmod +x ./cargo-green
         { ! ./cargo-green --version ; } | grep cargo-green
         mv ./cargo-green ~/.cargo/bin/
-
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      name: Retrieve saved builder data
+      uses: actions/download-artifact@v6
+      with:
+        name: builder-data
+        path: /home/runner/builder-cache
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      run: |
+        set -x
+        sudo mkdir -p $(cargo green supergreen sync data 2>/dev/null)
+        sudo mv -v /home/runner/builder-cache/* $(cargo green supergreen sync data 2>/dev/null)/
+        sudo chown -R root:root $(cargo green supergreen sync data 2>/dev/null)
     - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
@@ -220,7 +249,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
 
     - name: Retrieve saved bin
       uses: actions/download-artifact@v6
@@ -233,7 +261,18 @@ jobs:
         chmod +x ./cargo-green
         { ! ./cargo-green --version ; } | grep cargo-green
         mv ./cargo-green ~/.cargo/bin/
-
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      name: Retrieve saved builder data
+      uses: actions/download-artifact@v6
+      with:
+        name: builder-data
+        path: /home/runner/builder-cache
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      run: |
+        set -x
+        sudo mkdir -p $(cargo green supergreen sync data 2>/dev/null)
+        sudo mv -v /home/runner/builder-cache/* $(cargo green supergreen sync data 2>/dev/null)/
+        sudo chown -R root:root $(cargo green supergreen sync data 2>/dev/null)
     - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
@@ -349,7 +388,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
     - uses: docker/login-action@v3
       if: ${{ ! startsWith(github.ref, 'refs/heads/dependabot/') }}
       with:
@@ -365,7 +403,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
 
     - name: Retrieve saved bin
       uses: actions/download-artifact@v6
@@ -378,7 +415,18 @@ jobs:
         chmod +x ./cargo-green
         { ! ./cargo-green --version ; } | grep cargo-green
         mv ./cargo-green ~/.cargo/bin/
-
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      name: Retrieve saved builder data
+      uses: actions/download-artifact@v6
+      with:
+        name: builder-data
+        path: /home/runner/builder-cache
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      run: |
+        set -x
+        sudo mkdir -p $(cargo green supergreen sync data 2>/dev/null)
+        sudo mv -v /home/runner/builder-cache/* $(cargo green supergreen sync data 2>/dev/null)/
+        sudo chown -R root:root $(cargo green supergreen sync data 2>/dev/null)
     - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
@@ -594,7 +642,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
 
     - name: Retrieve saved bin
       uses: actions/download-artifact@v6
@@ -607,7 +654,18 @@ jobs:
         chmod +x ./cargo-green
         { ! ./cargo-green --version ; } | grep cargo-green
         mv ./cargo-green ~/.cargo/bin/
-
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      name: Retrieve saved builder data
+      uses: actions/download-artifact@v6
+      with:
+        name: builder-data
+        path: /home/runner/builder-cache
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      run: |
+        set -x
+        sudo mkdir -p $(cargo green supergreen sync data 2>/dev/null)
+        sudo mv -v /home/runner/builder-cache/* $(cargo green supergreen sync data 2>/dev/null)/
+        sudo chown -R root:root $(cargo green supergreen sync data 2>/dev/null)
     - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
@@ -887,7 +945,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
 
     - name: Retrieve saved bin
       uses: actions/download-artifact@v6
@@ -900,7 +957,18 @@ jobs:
         chmod +x ./cargo-green
         { ! ./cargo-green --version ; } | grep cargo-green
         mv ./cargo-green ~/.cargo/bin/
-
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      name: Retrieve saved builder data
+      uses: actions/download-artifact@v6
+      with:
+        name: builder-data
+        path: /home/runner/builder-cache
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      run: |
+        set -x
+        sudo mkdir -p $(cargo green supergreen sync data 2>/dev/null)
+        sudo mv -v /home/runner/builder-cache/* $(cargo green supergreen sync data 2>/dev/null)/
+        sudo chown -R root:root $(cargo green supergreen sync data 2>/dev/null)
     - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
@@ -1180,7 +1248,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
 
     - name: Retrieve saved bin
       uses: actions/download-artifact@v6
@@ -1193,7 +1260,18 @@ jobs:
         chmod +x ./cargo-green
         { ! ./cargo-green --version ; } | grep cargo-green
         mv ./cargo-green ~/.cargo/bin/
-
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      name: Retrieve saved builder data
+      uses: actions/download-artifact@v6
+      with:
+        name: builder-data
+        path: /home/runner/builder-cache
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      run: |
+        set -x
+        sudo mkdir -p $(cargo green supergreen sync data 2>/dev/null)
+        sudo mv -v /home/runner/builder-cache/* $(cargo green supergreen sync data 2>/dev/null)/
+        sudo chown -R root:root $(cargo green supergreen sync data 2>/dev/null)
     - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
@@ -1473,7 +1551,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
 
     - name: Retrieve saved bin
       uses: actions/download-artifact@v6
@@ -1486,7 +1563,18 @@ jobs:
         chmod +x ./cargo-green
         { ! ./cargo-green --version ; } | grep cargo-green
         mv ./cargo-green ~/.cargo/bin/
-
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      name: Retrieve saved builder data
+      uses: actions/download-artifact@v6
+      with:
+        name: builder-data
+        path: /home/runner/builder-cache
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      run: |
+        set -x
+        sudo mkdir -p $(cargo green supergreen sync data 2>/dev/null)
+        sudo mv -v /home/runner/builder-cache/* $(cargo green supergreen sync data 2>/dev/null)/
+        sudo chown -R root:root $(cargo green supergreen sync data 2>/dev/null)
     - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
@@ -1685,7 +1773,6 @@ jobs:
     - run: docker buildx build --help
     - run: podman version || true
     - run: cargo -Vv
-    - run: docker buildx prune --all --force
 
     - name: Retrieve saved bin
       uses: actions/download-artifact@v6
@@ -1698,7 +1785,18 @@ jobs:
         chmod +x ./cargo-green
         { ! ./cargo-green --version ; } | grep cargo-green
         mv ./cargo-green ~/.cargo/bin/
-
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      name: Retrieve saved builder data
+      uses: actions/download-artifact@v6
+      with:
+        name: builder-data
+        path: /home/runner/builder-cache
+    - if: ${{ false }} # TODO: just-sync'd builder cache ends up >500MB (above artifacts free tier)
+      run: |
+        set -x
+        sudo mkdir -p $(cargo green supergreen sync data 2>/dev/null)
+        sudo mv -v /home/runner/builder-cache/* $(cargo green supergreen sync data 2>/dev/null)/
+        sudo chown -R root:root $(cargo green supergreen sync data 2>/dev/null)
     - uses: actions/checkout@v6
 
     - name: Cache `cargo fetch`
